[phases.setup]
nixPkgs = [
    "python312",
    "glib",
    "nss",
    "nspr",
    "atk",
    "cups",
    "dbus",
    "libdrm",
    "pciutils",
    "mesa",
    "alsa-lib",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gtk3",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXcursor",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXi",
    "xorg.libXrandr",
    "xorg.libXrender",
    "xorg.libXScrnSaver",
    "xorg.libXtst",
    "xdg-utils"
]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["playwright install chromium"]