[phases.setup]
nixPkgs = [
    "python312",
    "glib",
    "nss",
    "nspr",
    "atk",
    "cups",
    "dbus",
    "libdrm",
    "libatasmart",
    "libgudev",
    "pciutils",
    "mesa",
    "libgbm",
    "alsa-lib",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gtk3",
    "xorg_libX11",
    "xorg_libXcomposite",
    "xorg_libXcursor",
    "xorg_libXdamage",
    "xorg_libXext",
    "xorg_libXfixes",
    "xorg_libXi",
    "xorg_libXrandr",
    "xorg_libXrender",
    "xorg_libXScrnSaver",
    "xorg_libXtst",
    "xorg_xkbfile",
    "xorg_libXxf86vm",
    "libxcb",
    "xorg_libxkbcommon",
    "xdg-utils"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["playwright install chromium"]