Ini, TOML
[phases.setup]
nixPkgs = [
    "python312",
    "glib",
    "nss",
    "nspr",
    "atk",
    "cups",
    "dbus",
    "libdrm",
    "libatasmart",
    "libgudev",
    "pciutils",
    "mesa",
    "libgbm",
    "alsa-lib",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gtk3",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXcursor",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXi",
    "xorg.libXrandr",
    "xorg.libXrender",
    "xorg.libXScrnSaver",
    "xorg.libXtst",
    "xorg.xkbfile",
    "xorg.libXxf86vm",
    "libxcb",
    "xorg.libxkbcommon",
    "xdg-utils"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["playwright install chromium"]